/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["me"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/private-keys": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listPrivateKeys"];
        put?: never;
        post: operations["createPrivateKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/private-keys/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Generates an ed25519 key pair server-side; the private key stays server-side, public key returned. */
        post: operations["generatePrivateKey"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/private-keys/{uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: components["parameters"]["Uuid"];
            };
            cookie?: never;
        };
        get: operations["getPrivateKey"];
        put?: never;
        post?: never;
        delete: operations["deletePrivateKey"];
        options?: never;
        head?: never;
        patch: operations["updatePrivateKey"];
        trace?: never;
    };
    "/servers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listServers"];
        put?: never;
        post: operations["createServer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/servers/{uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: components["parameters"]["Uuid"];
            };
            cookie?: never;
        };
        get: operations["getServer"];
        put?: never;
        post?: never;
        delete: operations["deleteServer"];
        options?: never;
        head?: never;
        patch: operations["updateServer"];
        trace?: never;
    };
    "/servers/{uuid}/validate": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: components["parameters"]["Uuid"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** @description Starts async validation; output streams on WS channel `server:<uuid>`. */
        post: operations["validateServer"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/servers/{uuid}/proxy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: components["parameters"]["Uuid"];
            };
            cookie?: never;
        };
        get: operations["getServerProxy"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateServerProxy"];
        trace?: never;
    };
    "/servers/{uuid}/proxy/start": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: components["parameters"]["Uuid"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["startServerProxy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/servers/{uuid}/proxy/stop": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: components["parameters"]["Uuid"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["stopServerProxy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/servers/{uuid}/proxy/restart": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: components["parameters"]["Uuid"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["restartServerProxy"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listProjects"];
        put?: never;
        /** @description Auto-creates a `production` environment. */
        post: operations["createProject"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: components["parameters"]["Uuid"];
            };
            cookie?: never;
        };
        get: operations["getProject"];
        put?: never;
        post?: never;
        delete: operations["deleteProject"];
        options?: never;
        head?: never;
        patch: operations["updateProject"];
        trace?: never;
    };
    "/projects/{uuid}/environments": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: components["parameters"]["Uuid"];
            };
            cookie?: never;
        };
        get: operations["listEnvironments"];
        put?: never;
        post: operations["createEnvironment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listApplications"];
        put?: never;
        post: operations["createApplication"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: components["parameters"]["Uuid"];
            };
            cookie?: never;
        };
        get: operations["getApplication"];
        put?: never;
        post?: never;
        delete: operations["deleteApplication"];
        options?: never;
        head?: never;
        patch: operations["updateApplication"];
        trace?: never;
    };
    "/applications/{uuid}/deploy": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: components["parameters"]["Uuid"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["deployApplication"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{uuid}/stop": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: components["parameters"]["Uuid"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["stopApplication"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{uuid}/restart": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: components["parameters"]["Uuid"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["restartApplication"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{uuid}/envs": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: components["parameters"]["Uuid"];
            };
            cookie?: never;
        };
        get: operations["listEnvVars"];
        put?: never;
        post: operations["createEnvVar"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/applications/{uuid}/envs/{env_uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: components["parameters"]["Uuid"];
                env_uuid: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteEnvVar"];
        options?: never;
        head?: never;
        patch: operations["updateEnvVar"];
        trace?: never;
    };
    "/applications/{uuid}/logs": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: components["parameters"]["Uuid"];
            };
            cookie?: never;
        };
        get: operations["getApplicationLogs"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deployments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listDeployments"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deployments/{uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: components["parameters"]["Uuid"];
            };
            cookie?: never;
        };
        get: operations["getDeployment"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deployments/{uuid}/cancel": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: components["parameters"]["Uuid"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post: operations["cancelDeployment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/settings": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["getSettings"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch: operations["updateSettings"];
        trace?: never;
    };
    "/api-tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["listApiTokens"];
        put?: never;
        post: operations["createApiToken"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api-tokens/{uuid}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: components["parameters"]["Uuid"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete: operations["deleteApiToken"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: operations["health"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ApiErrorBody: {
            code: string;
            message: string;
        };
        Health: {
            /** @enum {string} */
            status: "ok";
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        LoginResponse: {
            user: components["schemas"]["User"];
        };
        User: {
            id: string;
            email: string;
            name: string;
        };
        PrivateKey: {
            uuid: string;
            name: string;
            public_key: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at?: string;
        };
        PrivateKeyCreate: {
            name: string;
            /** @description write-only */
            private_key: string;
        };
        PrivateKeyUpdate: {
            name?: string;
            /** @description write-only */
            private_key?: string;
        };
        PrivateKeyGenerate: {
            name: string;
        };
        Server: {
            uuid: string;
            name: string;
            ip: string;
            port: number;
            user: string;
            private_key_uuid: string;
            reachable: boolean;
            usable: boolean;
            validation_logs?: string | null;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at?: string;
        };
        ServerCreate: {
            name: string;
            ip: string;
            /** @default 22 */
            port: number;
            /** @default root */
            user: string;
            private_key_uuid: string;
        };
        ServerUpdate: {
            name?: string;
            ip?: string;
            port?: number;
            user?: string;
            private_key_uuid?: string;
        };
        ValidateResponse: {
            job_uuid: string;
        };
        ProxyConfig: {
            proxy_type: string;
            proxy_status: string;
            proxy_custom_config?: string | null;
        };
        ProxyConfigUpdate: {
            proxy_custom_config?: string | null;
        };
        Project: {
            uuid: string;
            name: string;
            description?: string | null;
            environments?: components["schemas"]["Environment"][];
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at?: string;
        };
        ProjectCreate: {
            name: string;
            description?: string | null;
        };
        ProjectUpdate: {
            name?: string;
            description?: string | null;
        };
        Environment: {
            uuid: string;
            name: string;
            /** Format: date-time */
            created_at?: string;
        };
        EnvironmentCreate: {
            name: string;
        };
        /** @enum {string} */
        BuildPack: "nixpacks" | "dockerfile" | "static" | "docker_image" | "docker_compose";
        Application: {
            uuid: string;
            name: string;
            fqdn?: string | null;
            environment_uuid: string;
            project_uuid?: string;
            server_uuid: string;
            git_repository: string;
            git_branch: string;
            git_commit_sha: string;
            build_pack: components["schemas"]["BuildPack"];
            static_image?: string;
            docker_registry_image_name?: string | null;
            docker_registry_image_tag?: string | null;
            dockerfile_location?: string;
            docker_compose_location?: string;
            base_directory: string;
            publish_directory?: string | null;
            install_command?: string | null;
            build_command?: string | null;
            start_command?: string | null;
            ports_exposes: string;
            ports_mappings?: string | null;
            health_check_enabled?: boolean;
            health_check_path?: string;
            health_check_port?: string | null;
            health_check_host?: string;
            health_check_method?: string;
            health_check_return_code?: number;
            health_check_interval?: number;
            health_check_timeout?: number;
            health_check_retries?: number;
            health_check_start_period?: number;
            limits_memory?: string;
            limits_cpus?: string;
            custom_docker_run_options?: string | null;
            status: string;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at?: string;
        };
        ApplicationCreate: {
            project_uuid: string;
            environment_name: string;
            server_uuid: string;
            name: string;
            git_repository: string;
            /** @default main */
            git_branch: string;
            build_pack?: components["schemas"]["BuildPack"];
            /** @default 80 */
            ports_exposes: string;
            fqdn?: string | null;
            base_directory?: string;
            publish_directory?: string | null;
            dockerfile_location?: string;
            docker_compose_location?: string;
            static_image?: string;
            install_command?: string | null;
            build_command?: string | null;
            start_command?: string | null;
        };
        ApplicationUpdate: {
            name?: string;
            fqdn?: string | null;
            git_repository?: string;
            git_branch?: string;
            git_commit_sha?: string;
            build_pack?: components["schemas"]["BuildPack"];
            static_image?: string;
            dockerfile_location?: string;
            docker_compose_location?: string;
            base_directory?: string;
            publish_directory?: string | null;
            install_command?: string | null;
            build_command?: string | null;
            start_command?: string | null;
            ports_exposes?: string;
            ports_mappings?: string | null;
            health_check_enabled?: boolean;
            health_check_path?: string;
            limits_memory?: string;
            limits_cpus?: string;
            custom_docker_run_options?: string | null;
        };
        DeployRequest: {
            /** @default false */
            force_rebuild: boolean;
        };
        DeployResponse: {
            deployment_uuid: string;
        };
        EnvVar: {
            uuid: string;
            key: string;
            /** @description null once a shown-once variable has been read */
            value?: string | null;
            is_buildtime: boolean;
            is_literal: boolean;
            is_shown_once: boolean;
            /** Format: date-time */
            created_at: string;
            /** Format: date-time */
            updated_at?: string;
        };
        EnvVarCreate: {
            key: string;
            value: string;
            /** @default false */
            is_buildtime: boolean;
            /** @default false */
            is_literal: boolean;
            /** @default false */
            is_shown_once: boolean;
        };
        EnvVarUpdate: {
            key?: string;
            value?: string;
            is_buildtime?: boolean;
            is_literal?: boolean;
            is_shown_once?: boolean;
        };
        ContainerLogs: {
            logs: string;
        };
        /** @enum {string} */
        DeploymentStatus: "queued" | "in_progress" | "finished" | "failed" | "cancelled";
        Deployment: {
            uuid: string;
            application_uuid: string;
            server_uuid: string;
            status: components["schemas"]["DeploymentStatus"];
            commit_sha?: string | null;
            commit_message?: string | null;
            force_rebuild: boolean;
            rollback: boolean;
            /** Format: date-time */
            started_at?: string | null;
            /** Format: date-time */
            finished_at?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        /** @description Contract C3 log line (JSON field `order` maps to DB column `ord`) */
        LogLine: {
            /** Format: int64 */
            order: number;
            /** @enum {string} */
            kind: "stdout" | "stderr" | "info";
            content: string;
            hidden: boolean;
            batch: number;
            /** Format: date-time */
            timestamp: string;
        };
        DeploymentDetail: components["schemas"]["Deployment"] & {
            logs: components["schemas"]["LogLine"][];
        };
        InstanceSettings: {
            fqdn?: string | null;
            wildcard_domain?: string | null;
            registration_enabled: boolean;
        };
        InstanceSettingsUpdate: {
            fqdn?: string | null;
            wildcard_domain?: string | null;
            registration_enabled?: boolean;
        };
        ApiToken: {
            uuid: string;
            name: string;
            abilities: string[];
            /** Format: date-time */
            last_used_at?: string | null;
            /** Format: date-time */
            created_at: string;
        };
        ApiTokenCreate: {
            name: string;
        };
        ApiTokenCreated: {
            uuid: string;
            name: string;
            /** @description shown exactly once */
            token: string;
        };
    };
    responses: {
        /** @description Error envelope */
        Error: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ApiErrorBody"];
            };
        };
    };
    parameters: {
        Uuid: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Logged in; sets session cookie */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logged out */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    me: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Current user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Error"];
        };
    };
    listPrivateKeys: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Private keys */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrivateKey"][];
                };
            };
        };
    };
    createPrivateKey: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PrivateKeyCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrivateKey"];
                };
            };
            422: components["responses"]["Error"];
        };
    };
    generatePrivateKey: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PrivateKeyGenerate"];
            };
        };
        responses: {
            /** @description Generated */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrivateKey"];
                };
            };
        };
    };
    getPrivateKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: components["parameters"]["Uuid"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Private key */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrivateKey"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    deletePrivateKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: components["parameters"]["Uuid"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["Error"];
        };
    };
    updatePrivateKey: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: components["parameters"]["Uuid"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PrivateKeyUpdate"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PrivateKey"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    listServers: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Servers */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Server"][];
                };
            };
        };
    };
    createServer: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServerCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Server"];
                };
            };
            422: components["responses"]["Error"];
        };
    };
    getServer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: components["parameters"]["Uuid"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Server */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Server"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    deleteServer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: components["parameters"]["Uuid"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            404: components["responses"]["Error"];
        };
    };
    updateServer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: components["parameters"]["Uuid"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ServerUpdate"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Server"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    validateServer: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: components["parameters"]["Uuid"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Validation started */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ValidateResponse"];
                };
            };
        };
    };
    getServerProxy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: components["parameters"]["Uuid"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Proxy config */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProxyConfig"];
                };
            };
        };
    };
    updateServerProxy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: components["parameters"]["Uuid"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProxyConfigUpdate"];
            };
        };
        responses: {
            /** @description Saved */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ProxyConfig"];
                };
            };
        };
    };
    startServerProxy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: components["parameters"]["Uuid"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Proxy start queued */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    stopServerProxy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: components["parameters"]["Uuid"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Proxy stop queued */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    restartServerProxy: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: components["parameters"]["Uuid"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Proxy restart queued */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listProjects: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Projects */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"][];
                };
            };
        };
    };
    createProject: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
        };
    };
    getProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: components["parameters"]["Uuid"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Project with environments */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    deleteProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: components["parameters"]["Uuid"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateProject: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: components["parameters"]["Uuid"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ProjectUpdate"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Project"];
                };
            };
        };
    };
    listEnvironments: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: components["parameters"]["Uuid"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Environments */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Environment"][];
                };
            };
        };
    };
    createEnvironment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: components["parameters"]["Uuid"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnvironmentCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Environment"];
                };
            };
        };
    };
    listApplications: {
        parameters: {
            query?: {
                project_uuid?: string;
                environment_uuid?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Applications */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Application"][];
                };
            };
        };
    };
    createApplication: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Application"];
                };
            };
            422: components["responses"]["Error"];
        };
    };
    getApplication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: components["parameters"]["Uuid"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Application */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Application"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    deleteApplication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: components["parameters"]["Uuid"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateApplication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: components["parameters"]["Uuid"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApplicationUpdate"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Application"];
                };
            };
        };
    };
    deployApplication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: components["parameters"]["Uuid"];
            };
            cookie?: never;
        };
        requestBody?: {
            content: {
                "application/json": components["schemas"]["DeployRequest"];
            };
        };
        responses: {
            /** @description Deployment queued */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeployResponse"];
                };
            };
        };
    };
    stopApplication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: components["parameters"]["Uuid"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stop queued */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    restartApplication: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: components["parameters"]["Uuid"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Restart queued */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listEnvVars: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: components["parameters"]["Uuid"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Environment variables */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvVar"][];
                };
            };
        };
    };
    createEnvVar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: components["parameters"]["Uuid"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnvVarCreate"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvVar"];
                };
            };
            422: components["responses"]["Error"];
        };
    };
    deleteEnvVar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: components["parameters"]["Uuid"];
                env_uuid: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateEnvVar: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: components["parameters"]["Uuid"];
                env_uuid: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnvVarUpdate"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EnvVar"];
                };
            };
        };
    };
    getApplicationLogs: {
        parameters: {
            query?: {
                lines?: number;
            };
            header?: never;
            path: {
                uuid: components["parameters"]["Uuid"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Container logs (docker logs -n) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ContainerLogs"];
                };
            };
        };
    };
    listDeployments: {
        parameters: {
            query?: {
                application_uuid?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deployments */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Deployment"][];
                };
            };
        };
    };
    getDeployment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: components["parameters"]["Uuid"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deployment incl. logs[] (C3 LogLine) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["DeploymentDetail"];
                };
            };
            404: components["responses"]["Error"];
        };
    };
    cancelDeployment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: components["parameters"]["Uuid"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Cancel requested */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            409: components["responses"]["Error"];
        };
    };
    getSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Instance settings */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceSettings"];
                };
            };
        };
    };
    updateSettings: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InstanceSettingsUpdate"];
            };
        };
        responses: {
            /** @description Updated */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["InstanceSettings"];
                };
            };
        };
    };
    listApiTokens: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description API tokens (no secrets) */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiToken"][];
                };
            };
        };
    };
    createApiToken: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ApiTokenCreate"];
            };
        };
        responses: {
            /** @description Created; `token` is shown exactly once */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ApiTokenCreated"];
                };
            };
        };
    };
    deleteApiToken: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                uuid: components["parameters"]["Uuid"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Deleted */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    health: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Liveness */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
}
