-- PR preview deployments (Phase 3 wave-2, track p3-previews). Ports Coolify's
-- app/Models/ApplicationPreview.php table plus the application/settings columns
-- the webhook + preview deploy path reads (preview_url_template,
-- is_pr_deployments_(public_)enabled) and the per-provider manual webhook
-- secrets (github already added in 0006). Deployments carry a pull_request_id so
-- the engine can drive the PREVIEW path from the same queue row.

-- One preview environment per (application, pull request). Mirrors
-- ApplicationPreview: fqdn/status are (re)generated by the deploy engine, and
-- the row (with its volumes/network) is removed on PR close.
CREATE TABLE application_previews (
  id BIGSERIAL PRIMARY KEY,
  uuid TEXT UNIQUE NOT NULL,
  application_id BIGINT NOT NULL REFERENCES applications(id) ON DELETE CASCADE,
  pull_request_id INT NOT NULL,
  pull_request_html_url TEXT,
  pull_request_issue_comment_id BIGINT,
  fqdn TEXT,
  status TEXT NOT NULL DEFAULT 'exited',
  git_type TEXT,
  docker_compose_domains JSONB,
  docker_registry_image_tag TEXT,
  last_online_at TIMESTAMPTZ,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (application_id, pull_request_id)
);
CREATE INDEX application_previews_app ON application_previews (application_id);

-- A deployment may be a PREVIEW deploy of a pull request (pull_request_id != 0),
-- carrying the provider (git_type) so the engine can drive the preview path and
-- the PR-status comment.
ALTER TABLE deployments
  ADD COLUMN pull_request_id INT NOT NULL DEFAULT 0,
  ADD COLUMN git_type TEXT;

-- Instance-wide default for whether preview deployments from public/fork
-- contributors are allowed (Coolify InstanceSettings::is_pr_deployments_public_enabled).
ALTER TABLE instance_settings
  ADD COLUMN is_pr_deployments_public_enabled BOOLEAN NOT NULL DEFAULT false;

-- Per-application preview settings (Coolify ApplicationSetting) + the manual
-- webhook secrets for the non-GitHub providers (github added in 0006).
ALTER TABLE applications
  ADD COLUMN is_pr_deployments_enabled BOOLEAN NOT NULL DEFAULT true,
  ADD COLUMN is_pr_deployments_public_enabled BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN preview_url_template TEXT NOT NULL DEFAULT '{{pr_id}}.{{domain}}',
  ADD COLUMN manual_webhook_secret_gitlab_enc BYTEA,
  ADD COLUMN manual_webhook_secret_gitea_enc BYTEA,
  ADD COLUMN manual_webhook_secret_bitbucket_enc BYTEA;
